In [2]:
# %pylab inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

broken_df = pd.read_csv('comptagevelo20162.csv')
# Look at the first 3 rows
broken_df[:3]

fixed_df = pd.read_csv('comptagevelo20162.csv', sep=',', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date') 
# Look at the first 3 rows
fixed_df
# fixed_df[:3]
# # plt.show()
# fixed_df['Berri1'].plot()

,Unnamed: 1,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
Date,,,,,,,,,,,,,,,,,,,
2016-01-01,00:00,32,0,27,0.0,51.0,16,1,5,1,13,NaN,93,12,6,38,68,14,11
2016-01-02,00:00,68,0,6,0.0,93.0,25,2,16,6,9,NaN,141,16,11,67,106,30,14
2016-01-03,00:00,78,3,4,0.0,118.0,38,0,6,1,6,NaN,116,25,10,21,59,25,5
2016-01-04,00:00,118,6,60,2.0,165.0,80,0,46,0,3,NaN,202,49,9,4,99,111,29
2016-01-05,00:00,183,2,25,2.0,239.0,86,2,110,5,3,NaN,241,77,12,11,106,158,44
2016-01-06,00:00,305,3,14,45.0,378.0,116,11,126,3,3,NaN,302,120,53,29,189,224,62
2016-01-07,00:00,425,0,10,70.0,486.0,142,13,164,5,3,NaN,424,155,60,34,54,313,73
2016-01-08,00:00,393,1,14,77.0,439.0,138,10,131,3,18,NaN,432,157,61,75,91,310,66
2016-01-09,00:00,139,7,4,34.0,197.0,73,0,42,8,3,NaN,276,38,22,78,114,100,19
2016-01-10,00:00,136,30,11,59.0,151.0,46,12,55,10,6,NaN,252,42,13,80,196,73,9
2016-01-11,00:00,393,31,28,93.0,508.0,168,12,222,6,17,NaN,439,133,56,193,312,340,60
2016-01-12,00:00,398,12,21,129.0,451.0,152,18,206,8,20,NaN,422,139,46,125,253,286,73
2016-01-13,00:00,324,0,15,72.0,384.0,126,1,227,6,9,NaN,371,112,31,6,118,234,46
2016-01-14,00:00,347,1,2,76.0,437.0,134,16,142,8,9,NaN,390,106,29,1,124,274,45
2016-01-15,00:00,367,0,1,70.0,372.0,120,18,115,1,20,NaN,358,123,41,3,66,221,56
2016-01-16,00:00,113,0,5,20.0,145.0,42,6,29,7,14,NaN,227,32,12,2,88,70,11
2016-01-17,00:00,111,0,8,13.0,118.0,31,3,28,4,8,NaN,189,35,6,4,63,65,10
2016-01-18,00:00,340,0,2,72.0,339.0,111,11,99,1,12,NaN,350,105,22,1,235,151,38
2016-01-19,00:00,271,0,4,28.0,309.0,121,19,112,2,8,NaN,268,83,10,0,138,153,42
2016-01-20,00:00,376,0,12,83.0,432.0,139,31,139,0,7,NaN,415,110,63,119,222,232,76
2016-01-21,00:00,450,4,11,75.0,456.0,155,42,163,0,14,NaN,388,133,66,112,293,281,46
2016-01-22,00:00,400,5,55,78.0,415.0,155,26,185,0,23,NaN,465,147,75,117,299,230,49
2016-01-23,00:00,146,3,12,25.0,162.0,48,11,55,0,11,NaN,237,40,13,62,160,70,15
2016-01-24,00:00,116,4,18,27.0,145.0,41,6,57,0,3,NaN,213,43,7,67,155,58,18
2016-01-25,00:00,441,2,6,164.0,528.0,168,35,287,4,11,NaN,510,157,61,183,394,354,48
2016-01-26,00:00,417,15,7,109.0,543.0,174,42,257,4,15,NaN,421,153,44,166,303,311,64
2016-01-27,00:00,460,25,19,143.0,563.0,185,41,272,4,27,NaN,294,192,76,221,393,341,81
2016-01-28,00:00,419,22,15,132.0,582.0,181,35,263,9,27,NaN,386,170,80,269,388,396,53
2016-01-29,00:00,421,16,27,140.0,523.0,158,35,264,11,25,NaN,435,153,62,195,368,312,58
2016-01-30,00:00,136,6,9,35.0,212.0,56,15,76,11,11,NaN,245,52,6,106,160,119,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-02,00:00,993,597,130,669.0,NaN,441,262,934,72,348,NaN,1206,651,139,532,1089,664,98
2016-12-03,00:00,579,439,101,234.0,NaN,205,106,364,37,189,NaN,763,583,47,267,668,300,26
2016-12-04,00:00,646,498,100,303.0,NaN,237,139,377,116,289,NaN,881,329,54,267,678,288,43
2016-12-05,00:00,546,317,14,304.0,NaN,238,157,385,16,55,NaN,704,224,89,151,416,185,63
2016-12-06,00:00,693,377,22,347.0,NaN,233,134,464,12,62,NaN,672,254,81,184,622,245,71
2016-12-07,00:00,660,354,9,376.0,NaN,236,173,407,15,36,NaN,799,254,95,282,593,282,76
2016-12-08,00:00,836,495,16,471.0,NaN,308,203,541,19,64,NaN,1076,390,114,364,814,444,105
2016-12-09,00:00,546,292,15,164.0,NaN,168,83,286,9,45,NaN,633,220,79,234,416,162,58
2016-12-10,00:00,275,185,2,63.0,NaN,85,18,142,12,14,NaN,470,69,31,135,387,53,25
2016-12-11,00:00,238,207,6,56.0,NaN,97,28,125,15,55,NaN,438,71,26,85,312,38,17
2016-12-12,00:00,353,246,10,91.0,NaN,105,59,196,1,19,NaN,498,115,36,12,429,47,19
2016-12-13,00:00,561,308,6,66.0,NaN,166,95,267,1,44,NaN,609,225,68,9,434,183,35
2016-12-14,00:00,559,283,7,220.0,NaN,175,132,268,14,13,NaN,700,201,69,56,309,199,50
2016-12-15,00:00,443,234,11,203.0,NaN,156,88,196,5,17,NaN,543,153,46,38,321,163,43
2016-12-16,00:00,271,159,29,127.0,NaN,116,66,138,8,24,NaN,362,123,48,33,315,118,33
2016-12-17,00:00,127,97,6,14.0,NaN,42,8,45,4,3,NaN,231,40,11,9,198,29,12
2016-12-18,00:00,93,69,2,6.0,NaN,47,22,24,6,16,NaN,200,29,12,6,248,25,6
2016-12-19,00:00,384,162,2,53.0,NaN,97,88,169,5,99,NaN,480,107,46,1,222,124,25
2016-12-20,00:00,460,160,6,175.0,NaN,146,93,227,4,6,NaN,543,143,72,17,304,189,46
2016-12-21,00:00,461,125,6,223.0,NaN,156,127,266,11,114,NaN,669,186,60,36,433,190,64
2016-12-22,00:00,427,101,12,180.0,NaN,113,79,204,16,0,NaN,539,167,67,37,348,162,39
2016-12-23,00:00,274,87,14,104.0,NaN,122,56,154,14,0,NaN,421,128,33,61,320,134,26
2016-12-24,00:00,78,41,3,28.0,NaN,30,13,30,5,0,NaN,185,22,7,13,95,31,4
2016-12-25,00:00,44,24,8,2.0,NaN,22,3,11,1,0,NaN,104,11,9,9,63,10,7
2016-12-26,00:00,53,14,3,12.0,NaN,37,11,4,2,0,NaN,103,21,7,9,73,17,6
2016-12-27,00:00,137,42,1,30.0,NaN,57,26,33,8,0,NaN,205,59,12,5,136,40,11
2016-12-28,00:00,181,55,1,70.0,NaN,91,44,68,4,0,NaN,288,85,24,16,171,76,19
2016-12-29,00:00,120,33,5,35.0,NaN,46,18,41,8,0,NaN,203,53,13,6,208,38,14
2016-12-30,00:00,120,59,13,2.0,NaN,53,29,53,3,10,NaN,72,55,15,0,218,68,3
2016-12-31,00:00,52,26,2,135.0,NaN,23,11,12,6,0,NaN,122,16,4,17,102,16,3